Nab 452 EntityMeta初期化時の内部エラーをログに出力
nablarch/nablarch-common-dao pull request #29
Opened 2022-02-21 10:34 UTC by fyamvbf

2022-02-22 02:59 UTC, kumagoro1202 requested changes

2022-02-22 02:59 UTC, kumagoro1202 commented on src/test/java/nablarch/common/dao/EntityMetaTest.java
> +
外部要因によってテストの結果が変わってしまう状態です。
モック化するなどテストの前提条件はテストの中で示せるようにしてください。

2022-02-22 02:59 UTC, kumagoro1202 commented on src/main/java/nablarch/common/dao/EntityMeta.java
> +            if (SystemRepository.getBoolean("nablarch.entityMeta.showInternalErrorLog")) {
InternalErrorはNablarchのクラスとして存在するので別の語句を使うようにしてください。

2022-02-22 02:59 UTC, kumagoro1202 commented on src/main/java/nablarch/common/dao/EntityMeta.java
> +            if (SystemRepository.getBoolean("nablarch.entityMeta.showInternalErrorLog")) {
なぜこの判定をしているのかコメントに残してください。

2022-02-22 02:59 UTC, kumagoro1202 commented on src/test/java/nablarch/common/dao/EntityMetaTest.java
> +                "java.lang.IllegalArgumentException: specified database connection name is not register in thread local. connection name = [transaction]");
assertLogというメソッド化していますが、OnMemoryLogWriter.assertLogContainsを直接使うのと比べて意図が明確になるわけでもなく再利用できて生産性が上がるということもなく、メソッド化するメリットがないと思います。
また、OnMemoryLogWriterからWRITER_NAMEでメッセージを取得することが隠蔽されているので何とassertするのかも読み取りにくいので直接OnMemoryLogWriter.assertLogContainsを使うようにしてください。

2022-02-22 02:59 UTC, kumagoro1202 commented on src/test/java/nablarch/common/dao/EntityMetaTest.java
> +        System.setProperty("nablarch.log.filePath", "classpath:nablarch/core/log/log-mock.properties");
これは何のためですか？
nablarch.log.filePathというプロパティはLoggerManagerが使いますがstaticなフィールドの初期化に使っているのでテストのタイミングでこのプロパティ変えても読み取られることがないはずです。

2022-02-22 02:59 UTC, kumagoro1202 commented on src/test/java/nablarch/common/dao/EntityMetaTest.java
> +        clearLog();
clearLogというのは毎回テスト実行前に保証されているべき動作なので@Beforeなどで実行するべきです。

2022-02-22 02:59 UTC, kumagoro1202 commented on src/test/java/nablarch/common/dao/EntityMetaTest.java
> +        setSystemRepositoryParamShowInternalErrorLog(false); //デフォルトの状態=falseに戻す
デフォルトの状態に戻すのも各テストで個別に書くのではなく＠Afterなどで実装するべきです。

2022-02-22 02:59 UTC, kumagoro1202 commented on src/test/java/nablarch/common/dao/EntityMetaTest.java
> +    }
これは単にactualLogsのsizeが0であることをassertするだけで良いのでは？
またテスト失敗を宣言する時は普通はAssertionErrorをnewするのではなくAssert.fail(String message)を使います。
AssertionErrorの組み立てもコード量多く大きな意味があるように見えて何の意味もないという良くないパターンです。

2022-02-22 07:27 UTC, fyamvbf commented on src/test/java/nablarch/common/dao/EntityMetaTest.java
> +
モック化実施　https://github.com/nablarch/nablarch-common-dao/pull/29/commits/b3e7a0549c0ee90b9ad3b80a4b1b76cb61451cc1

2022-02-22 07:28 UTC, fyamvbf commented on src/test/java/nablarch/common/dao/EntityMetaTest.java
> +        clearLog();
共通処理の切り出し実施　https://github.com/nablarch/nablarch-common-dao/pull/29/commits/358066e07025bd3141c5dc79e6c321558f216f56

2022-02-22 07:28 UTC, fyamvbf commented on src/test/java/nablarch/common/dao/EntityMetaTest.java
> +        setSystemRepositoryParamShowInternalErrorLog(false); //デフォルトの状態=falseに戻す
共通処理の切り出し実施　https://github.com/nablarch/nablarch-common-dao/pull/29/commits/358066e07025bd3141c5dc79e6c321558f216f56

2022-02-22 07:30 UTC, fyamvbf commented on src/test/java/nablarch/common/dao/EntityMetaTest.java
> +        System.setProperty("nablarch.log.filePath", "classpath:nablarch/core/log/log-mock.properties");
OnMemoryLogWriter導入の際に誤って埋め込んでしまった無意味な処理でした。→削除実施　https://github.com/nablarch/nablarch-common-dao/pull/29/commits/e81c4923aa8c278fda8141435b1a78501ca14611

2022-02-22 07:38 UTC, fyamvbf commented on src/main/java/nablarch/common/dao/EntityMeta.java
> +            if (SystemRepository.getBoolean("nablarch.entityMeta.showInternalErrorLog")) {
名称変更実施　https://github.com/nablarch/nablarch-common-dao/pull/29/commits/bf57f760359eed961ed4cc7fd4d1601774af7853

2022-02-22 09:21 UTC, fyamvbf commented on src/test/java/nablarch/common/dao/EntityMetaTest.java
> +                "java.lang.IllegalArgumentException: specified database connection name is not register in thread local. connection name = [transaction]");
上記の通り対応　https://github.com/nablarch/nablarch-common-dao/pull/29/commits/b466c341092c8cf581ec7a02e55016a63860cd8c

2022-02-22 09:22 UTC, fyamvbf commented on src/test/java/nablarch/common/dao/EntityMetaTest.java
> +    }
上記の通り対応して、インライン化　https://github.com/nablarch/nablarch-common-dao/pull/29/commits/b466c341092c8cf581ec7a02e55016a63860cd8c

2022-02-22 09:41 UTC, fyamvbf commented
デフォルトの動作はログは出力する。
明示的に隠す指定があった場合だけログを隠すように修正。
https://github.com/nablarch/nablarch-common-dao/pull/29/commits/1f227777aa842255220265341864c4e00e7bcdc4

2022-02-22 09:51 UTC, fyamvbf commented on src/main/java/nablarch/common/dao/EntityMeta.java
> +            if (SystemRepository.getBoolean("nablarch.entityMeta.showInternalErrorLog")) {
コメント追記　https://github.com/nablarch/nablarch-common-dao/pull/29/commits/533859c284025e4927e8aa4c9b67c25c890bee7e

2022-02-22 10:17 UTC, kumagoro1202 requested changes

2022-02-22 10:17 UTC, kumagoro1202 commented on src/main/java/nablarch/common/dao/EntityMeta.java
> +            // このエラーログの出力を無効化したい場合は環境設定ファイルに、以下の記述を追加すること。
エラーログじゃなくWARNINGです。単に"ログ"でいいと思います。

2022-02-22 10:17 UTC, kumagoro1202 commented on src/main/java/nablarch/common/dao/EntityMeta.java
> +            if (!SystemRepository.getBoolean("nablarch.entityMeta.hideCauseExceptionLog")) {
!によるネガティブの反転は読みにくくなるのでできるなら
`isShowCausedException()`とかのメソッドに切り出したほうが読みやすいと思いました。

2022-02-22 10:17 UTC, kumagoro1202 commented on src/test/java/nablarch/common/dao/EntityMetaTest.java
> +        clearLog();
BeforeとAfter両方でclearLogをやるのは冗長だと思います。
そして1行になるのでclearLogをメソッドに切り出す意味もなくなると思います。

2022-02-22 10:17 UTC, kumagoro1202 commented on src/test/java/nablarch/common/dao/EntityMetaTest.java
> +        };
モック化をBeforeの中でやるのは良くないです。
このテストクラスに書くテストは漏れなくモック化された状態であるべきならBeforeに書くべきですが、このクラスはそんなことないですよね？たまたま現状のテストは全部モック化されてても問題にならないだけです。sortIdColumnsが正常に動く場合のテストができなくなるのでこういうものはBeforeに書かずテストメソッド内に書いてください。

2022-02-22 10:17 UTC, kumagoro1202 commented on src/test/java/nablarch/common/dao/EntityMetaTest.java
> +        OnMemoryLogWriter.assertLogContains(WRITER_NAME, new String[] {
assertLogContainsの引数は可変引数です。`new String[]{}`は不要です。

2022-02-24 02:48 UTC, fyamvbf commented on src/main/java/nablarch/common/dao/EntityMeta.java
> +            // このエラーログの出力を無効化したい場合は環境設定ファイルに、以下の記述を追加すること。
修正しました　https://github.com/nablarch/nablarch-common-dao/pull/29/commits/347c8c2a299b9dcfa924dd42c5b92c6cfeaea2de

2022-02-24 02:49 UTC, fyamvbf commented on src/main/java/nablarch/common/dao/EntityMeta.java
> +            if (!SystemRepository.getBoolean("nablarch.entityMeta.hideCauseExceptionLog")) {
修正しました　https://github.com/nablarch/nablarch-common-dao/pull/29/commits/92ebd029ed88bd562b8fd84ef3a4ccdf8f83d7c5

2022-02-24 04:50 UTC, fyamvbf commented on src/test/java/nablarch/common/dao/EntityMetaTest.java
> +        clearLog();
修正しました　https://github.com/nablarch/nablarch-common-dao/pull/29/commits/bb4d5614cb75181c654690ae1a610c143a231186

2022-02-24 04:50 UTC, fyamvbf commented on src/test/java/nablarch/common/dao/EntityMetaTest.java
> +        };
修正しました　https://github.com/nablarch/nablarch-common-dao/pull/29/commits/bb4d5614cb75181c654690ae1a610c143a231186

2022-02-24 04:50 UTC, fyamvbf commented on src/test/java/nablarch/common/dao/EntityMetaTest.java
> +        OnMemoryLogWriter.assertLogContains(WRITER_NAME, new String[] {
修正しました　https://github.com/nablarch/nablarch-common-dao/pull/29/commits/bb4d5614cb75181c654690ae1a610c143a231186

2022-02-24 05:16 UTC, fyamvbf commented
既存テストケースの修正もしておきました　https://github.com/nablarch/nablarch-common-dao/pull/29/commits/387c1d7c9e982adfd7df88d6464e7f738f3727bb

2022-02-24 05:58 UTC, kumagoro1202 requested changes

2022-02-24 05:58 UTC, kumagoro1202 commented on src/test/java/nablarch/common/dao/EntityMetaTest.java
> +    public void setUp() throws Exception {
全メソッドに`throws Exception`をつけていますがお作法というわけではないです。
不要な`throws Exception`はつけないでください。

2022-02-24 05:58 UTC, kumagoro1202 commented on src/main/java/nablarch/common/dao/EntityMeta.java
> +     * ログの出力を抑制したいときだけ環境設定ファイル上でnablarch.entityMeta.hideCauseExceptionLogにtrueを設定する仕様である。この処理では未設定時、false指定時はログを出力する(=true)と判定する。
プロパティ名が2回出てきて文字数多く読みにくいと感じました。
「1行目は原因となった例外をログに出力するかどうか判定する。」とかでいいんじゃないでしょうか。
2つ目のパラグラフも「設定する仕様である」という記述に違和感を覚えました。このメソッドの説明にはなっていないので。
「デフォルトではログを出力しない。
nablarch.entityMeta.hideCauseExceptionLogというプロパティにtrueが設定されていた場合はログ出力を抑制する。」
とかどうでしょう。

2022-02-24 08:49 UTC, fyamvbf commented on src/main/java/nablarch/common/dao/EntityMeta.java
> +     * ログの出力を抑制したいときだけ環境設定ファイル上でnablarch.entityMeta.hideCauseExceptionLogにtrueを設定する仕様である。この処理では未設定時、false指定時はログを出力する(=true)と判定する。
コメント修正しました　https://github.com/nablarch/nablarch-common-dao/pull/29/commits/c3f61619fa49c6b0c3f599ff726c163a27d100e9

2022-02-24 08:49 UTC, fyamvbf commented on src/test/java/nablarch/common/dao/EntityMetaTest.java
> +    public void setUp() throws Exception {
不要記述削除しました　https://github.com/nablarch/nablarch-common-dao/pull/29/commits/19706d554b7d8cbee35cb6e810a78d8d4ba27125

2022-02-24 10:03 UTC, merged