UniversalDaoでNoDataExceptionを出さないメソッドを用意する
nablarch/nablarch-common-dao pull request #30
Opened 2023-02-13 07:32 UTC by takikunxo

2023-02-13 08:37 UTC, kumagoro1202 requested changes

2023-02-13 08:37 UTC, kumagoro1202 commented on src/main/java/nablarch/common/dao/BasicDaoContext.java
> +     * @throws IllegalArgumentException (主キーの数と指定した条件数が一致しない場合)
主キーの**カラム**数としてもらった方がいいと思いました。

2023-02-13 08:37 UTC, kumagoro1202 commented on src/main/java/nablarch/common/dao/BasicDaoContext.java
> +     * @return エンティティオブジェクト
`@return`は`@inheritDoc`で親であるDaoContextから引き継がれるので不要です。

2023-02-13 08:37 UTC, kumagoro1202 commented on src/main/java/nablarch/common/dao/BasicDaoContext.java
> +     * @throws NoDataException (検索条件に該当するレコードが存在しない場合)
findById同様`@inheritDoc`を使って親のJavadocを引き継ぐようにしてください。そのうえでこの実装ではNoDataExceptionを出すことを記載してください。

2023-02-13 08:37 UTC, kumagoro1202 commented on src/main/java/nablarch/common/dao/UniversalDao.java
> +     * <p/>
findAllBySqlFileのように詳細はfindBySqlFile参照として良いです。
NoDataExceptionを送出する代わりにnullを返す以外はfindBySqlFileと同じですみたいなことを書いておいて欲しいです。

2023-02-14 00:56 UTC, takikunxo commented on src/main/java/nablarch/common/dao/UniversalDao.java
> +     * <p/>
[こちら](https://github.com/nablarch/nablarch-common-dao/pull/30/commits/964ccc68c01d4c9e2378290a11f1f69db6201032)で記載を修正しました。

2023-02-14 00:57 UTC, takikunxo commented on src/main/java/nablarch/common/dao/BasicDaoContext.java
> +     * @throws NoDataException (検索条件に該当するレコードが存在しない場合)
[こちら](https://github.com/nablarch/nablarch-common-dao/pull/30/commits/703e606f051a34dd6c10aec305737d2544a3889e)と[こちら](https://github.com/nablarch/nablarch-common-dao/pull/30/commits/ea9dac34bbc7a62d99239633b6141f3512191f24)で記載を修正しました（styleのみの修正）。

2023-02-14 00:58 UTC, takikunxo commented on src/main/java/nablarch/common/dao/BasicDaoContext.java
> +     * @throws IllegalArgumentException (主キーの数と指定した条件数が一致しない場合)
[こちら](https://github.com/nablarch/nablarch-common-dao/pull/30/commits/13f4da5aa68955b3962c43c9b27f3d96a2b3fff9)で修正しました(styleのみの修正)。

2023-02-14 02:38 UTC, kumagoro1202 approved these changes

2023-02-14 02:38 UTC, merged